// Builds the Equinox daily puzzle bank.
//
// Every board is generated, carved and verified here, offline, then committed
// as src/shared/equinox-bank.ts. The server never generates a puzzle — it only
// reads this file — so a board that fails verification simply never exists.
//
//   npm run equinox-bank            # default: 400 boards
//   npm run equinox-bank -- 800     # more

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  EMPTY, encodePuzzle, generatePuzzle, mulberry32, verifyPuzzle, type EncodedPuzzle,
} from '../src/shared/equinox-core';

const N = 6;
const COUNT = Number(process.argv[2] ?? 400);
const OUT = resolve(process.cwd(), 'src/shared/equinox-bank.ts');

// Boards this open or this crowded are technically fine but no fun: too few
// clues reads as a blank grid, too many leaves nothing to work out.
const MIN_CLUES = 8;
const MAX_CLUES = 20;

type Entry = EncodedPuzzle & { clueCount: number };

const bank: Entry[] = [];
const seen = new Set<string>();
const clueHistogram = new Map<number, number>();
let seed = 0;
let rejected = 0;

const started = Date.now();
while (bank.length < COUNT) {
  if (seed > COUNT * 500) throw new Error(`stalled at ${bank.length}/${COUNT} boards`);
  const gen = generatePuzzle(N, seed++);
  if (!gen) { rejected++; continue; }

  const { puzzle, solution, clueCount } = gen;
  if (clueCount < MIN_CLUES || clueCount > MAX_CLUES) { rejected++; continue; }

  // generatePuzzle already gated this board. Check it again anyway — this file
  // is the last place a bad puzzle can be caught before it ships.
  const check = verifyPuzzle(puzzle, solution);
  if (!check.ok) throw new Error(`verified puzzle failed re-check: ${check.reason}`);
  if (puzzle.clues.every(c => c !== EMPTY)) throw new Error('puzzle has no empty cells');

  const enc = encodePuzzle(puzzle);
  const key = `${enc.clues}|${enc.numbers}`;
  if (seen.has(key)) { rejected++; continue; }
  seen.add(key);

  bank.push({ ...enc, clueCount });
  clueHistogram.set(clueCount, (clueHistogram.get(clueCount) ?? 0) + 1);
}

// Fixed shuffle so consecutive days don't arrive in generation order (which
// trends easy-to-hard as the seed climbs).
const rng = mulberry32(0x5eed_1eaf);
for (let i = bank.length - 1; i > 0; i--) {
  const j = Math.floor(rng() * (i + 1));
  [bank[i], bank[j]] = [bank[j]!, bank[i]!];
}

const lines = bank.map(e => `  { clues: '${e.clues}', numbers: '${e.numbers}' },`).join('\n');
const file = `// GENERATED by scripts/gen-equinox-bank.ts — do not edit by hand.
// ${bank.length} Equinox boards, each verified to have exactly one answer and
// to be solvable by deduction alone. Regenerate with \`npm run equinox-bank\`.
import type { EncodedPuzzle } from './equinox-core';

export const EQUINOX_BANK_N = ${N};

export const EQUINOX_BANK: readonly Omit<EncodedPuzzle, 'n'>[] = [
${lines}
] as const;
`;

writeFileSync(OUT, file);

const counts = [...clueHistogram.entries()].sort((a, b) => a[0] - b[0]);
const avg = bank.reduce((s, e) => s + e.clueCount, 0) / bank.length;
console.log(`${bank.length} boards in ${((Date.now() - started) / 1000).toFixed(1)}s (${rejected} discarded)`);
console.log(`clues: min ${counts[0]![0]}, max ${counts[counts.length - 1]![0]}, avg ${avg.toFixed(1)}`);
console.log(counts.map(([c, n]) => `${c}:${n}`).join('  '));
console.log(`wrote ${OUT}`);
